### ISSUE TITLE
use only mockery.yaml

### ISSUE THREAD

**Issue by glimchb** [opiproject/godpu#282]
for example:
```
with-expecter: True
boilerplate-file: mocks/boilerplate.txt
packages:
  github.com/opiproject/godpu/grpc:
    interfaces:
      Connector:
    config:
      dir: grpc
  github.com/opiproject/godpu/inventory:
    interfaces:
      InvClient:
    config:
      dir: inventory
  github.com/opiproject/godpu/network:
    interfaces:
      EvpnClient:
    config:
      dir: network
  github.com/opiproject/opi-api/common/v1/gen/go:
    interfaces:
      InventorySvcClient:
  github.com/opiproject/opi-api/network/evpn-gw/v1alpha1/gen/go:
    interfaces:
      SviServiceClient:
      VrfServiceClient:
      BridgePortServiceClient:
      LogicalBridgeServiceClient:
```

and then Makefile rule becomes just one liner
```
mock-generate:
	@echo "  >  Starting mock code generation..."
	# Generate mocks for exported interfaces
	mockery --config=mocks/.mockery.yaml
```
